server:
  port: 8080

#配置数据源
spring:
  datasource:
    url: jdbc:mysql://47.101.171.217/saasmall?useUnicode=true&characterEncoding=utf8
    username: root
    password: 20020118
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true

#指定mybatis映射文件的地址
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.youko.customerfrontstage.bean
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  # 数据库方言 mysql
  helper-dialect: mysql

  # 分页参数合理化
  # 默认是false。
  # 启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页；
  # 禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
  reasonable: true

  # 支持通过 Mapper 接口参数来传递分页参数
  # 默认值 false
  support-methods-arguments: true

  # 为了支持startPage(Object params)方法，增加了该参数来配置参数映射，
  # 用于从对象中根据属性名取值
  #  默认值为 countSql
  params: count=countSql




